<h2>Swap columns 1 and 2 in the array arr.</h2>

In [5]:
import numpy as np
print(arr)
arr = np.arange(9).reshape(3,3)
arr[:, [1,0,2]]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

<h2>Swap rows 1 and 2 in the array arr:</h2>

In [6]:
arr = np.arange(9).reshape(3,3)
print(arr)
arr[[1,0,2], :]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

<h2>Reverse the rows of a 2D array arr.</h2>

In [7]:
arr = np.arange(9).reshape(3,3)
print(arr)
arr[::-1]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

<h2>Reverse the columns of a 2D array arr.</h2>

In [8]:
arr = np.arange(9).reshape(3,3)
print(arr)
arr[:, ::-1]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

<h2>Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.</h2>

In [9]:
arr = np.arange(9).reshape(3,3)
print(arr)
rand_arr = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))
rand_arr = np.random.uniform(5,10, size=(5,3))
rand_arr

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[9.64759789, 7.10151703, 6.56644925],
       [7.00510103, 5.54277746, 7.25845441],
       [7.04926873, 5.35033954, 6.72662672],
       [8.92350613, 9.36414498, 6.29048154],
       [7.71986533, 9.57685139, 6.84603611]])

<h2>Print or show only 3 decimal places of the numpy array rand_arr.</h2>

In [11]:
rand_arr = np.random.random((5,3))
print(rand_arr)
rand_arr = np.random.random([5,3])
np.set_printoptions(precision=3)
rand_arr[:4]

[[0.982 0.731 0.103]
 [0.059 0.71  0.389]
 [0.175 0.603 0.955]
 [0.21  0.762 0.306]
 [0.158 0.141 0.115]]


array([[0.755, 0.534, 0.215],
       [0.911, 0.065, 0.328],
       [0.535, 0.419, 0.817],
       [0.367, 0.719, 0.891]])

<h2>Pretty print rand_arr by suppressing the scientific notation (like 1e10)</h2>

In [12]:
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr

array([[5.434e-04, 2.784e-04, 4.245e-04],
       [8.448e-04, 4.719e-06, 1.216e-04],
       [6.707e-04, 8.259e-04, 1.367e-04]])

In [13]:
np.set_printoptions(suppress=False)

In [14]:
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr

array([[5.434e-04, 2.784e-04, 4.245e-04],
       [8.448e-04, 4.719e-06, 1.216e-04],
       [6.707e-04, 8.259e-04, 1.367e-04]])

In [15]:
np.set_printoptions(suppress=True, precision=6)  # precision is optional
rand_arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

<h2>Limit the number of items printed in python numpy array a to a maximum of 6 elements.</h2>

In [17]:
np.set_printoptions(threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

<h2>Import the iris dataset keeping the text intact.</h2>

In [27]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [28]:
iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

<h2>Extract the text column species from the 1D iris imported in previous question.</h2>

In [31]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
iris_1d.shape

<ipython-input-31-7eb592017e87>:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)


(150,)

In [32]:
species = np.array([row[4] for row in iris_1d])
species[:5]

array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa'], dtype='|S18')

<h2>Convert the 1D iris to 2D array iris_2d by omitting the species text field.</h2>

In [33]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)

<ipython-input-33-1bd890663978>:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)


In [34]:
iris_2d = np.array([row.tolist()[:4] for row in iris_1d])
iris_2d[:4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

In [35]:
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[:4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

<h2>Find the mean, median, standard deviation of iris's sepallength (1st column)</h2>

In [36]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

In [37]:
mu, med, sd = np.mean(sepallength), np.median(sepallength), np.std(sepallength)
print(mu, med, sd)

5.843333333333334 5.8 0.8253012917851409


<h2>Create a normalized form of iris's sepallength whose values range exactly between 0 and 1 so that the minimum has value 0 and maximum has value 1.</h2>

In [38]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

In [39]:
Smax, Smin = sepallength.max(), sepallength.min()
S = (sepallength - Smin)/(Smax - Smin)

In [40]:
S = (sepallength - Smin)/sepallength.ptp()  # Thanks, David Ojeda!
print(S)

[0.222222 0.166667 0.111111 ... 0.611111 0.527778 0.444444]


<h2>Compute the softmax score of sepallength</h2>

In [41]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.array([float(row[0]) for row in iris])

In [42]:
def softmax(x):
    """Compute softmax values for each sets of scores in x.
    https://stackoverflow.com/questions/34968722/how-to-implement-the-softmax-function-in-python"""
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0)

softmax(sepallength)

array([0.00222 , 0.001817, 0.001488, ..., 0.009001, 0.006668, 0.00494 ])

<h1>End</h1>