<h2>Import numpy as np and print the version number.</h2>

In [1]:
import numpy as np
np.__version__

'1.19.4'

<h2> Create a 1D array of numbers from 0 to 9</h2>

In [6]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

<h2>Create a 3×3 numpy array of all True’s</h2>

In [7]:
np.full((3,3),True, dtype ='bool')

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [8]:
np.ones((3,3),dtype = 'bool')

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

<h2>Extract all odd numbers from array</h2>

In [9]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2 == 0]

array([0, 2, 4, 6, 8])

In [12]:
a = (arr%2 == 0)
arr[a]

array([0, 2, 4, 6, 8])

<h2>Replace all odd numbers in arr with -1</h2>

In [14]:
a = (arr%2) == 0
arr[a] = -1
arr

array([-1,  1, -1,  3, -1,  5, -1,  7, -1,  9])

<h2>Replace all odd numbers in arr with -1 without changing arr</h2>

In [17]:
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(out)
arr

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

<h2>Convert a 1D array to a 2D array with 2 rows</h2>

In [18]:
arr.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

<h2>Stack arrays a and b vertically</h2>

In [19]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [22]:
# Method 1:
np.concatenate([a, b], axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [23]:
# Method 2:
np.vstack([a, b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [24]:
# Method 3:
np.r_[a, b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

<h2>Stack the arrays a and b horizontally.</h2>

In [25]:
# Method 1:
np.concatenate([a, b], axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [26]:
# Method 2:
np.hstack([a, b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [27]:
# Method 3:
np.c_[a, b]


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

<h2>Create the following pattern without hardcoding. Use only numpy functions and the below input array a.</h2>

In [28]:
a = np.array([1,2,3])

In [29]:
#Desired Output:

#> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [30]:
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

<h2>Get the common items between a and b</h2>

In [36]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [37]:
np.intersect1d(a,b)

array([2, 4])

<h2>From array a remove all items present in array b</h2>

In [38]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [39]:
np.setdiff1d(a,b)

array([1, 2, 3, 4])

<h2>Get the positions where elements of a and b match</h2>

In [40]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [41]:
np.where(a == b)

(array([1, 3, 5, 7], dtype=int32),)

<h2>Get all items between 5 and 10 from a.</h2>

In [42]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [44]:
# method 1
index = np.where((a >= 5) & (a <= 10))
a[index]

array([ 6,  9, 10])

In [45]:
# Method 2:
index = np.where(np.logical_and(a>=5, a<=10))
a[index]

array([ 6,  9, 10])

In [46]:
a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])

<h2>Convert the function maxx that works on two scalars, to work on two arrays.</h2>

In [47]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)

5

In [48]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])

In [49]:
<h1>End<h1>

SyntaxError: invalid syntax (<ipython-input-49-a780eb8983fc>, line 1)